// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdWRL0xg9_DU9ZugmXnMWeJ0FLMAxzDz8',
    appId: '1:20913898706:web:69482a7a2e65e8fb45190b',
    messagingSenderId: '20913898706',
    projectId: 'sawit-pro-ea577',
    authDomain: 'sawit-pro-ea577.firebaseapp.com',
    storageBucket: 'sawit-pro-ea577.appspot.com',
    measurementId: 'G-9YTPSJQ42Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD89EcTMBcrG1c47wuf0furGOXfohcVhFI',
    appId: '1:20913898706:android:dcb5d25f22c2139845190b',
    messagingSenderId: '20913898706',
    projectId: 'sawit-pro-ea577',
    storageBucket: 'sawit-pro-ea577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBZZdI3qEfnHkyZbgD7z4OxWcLu2WiVY',
    appId: '1:20913898706:ios:733207478120196545190b',
    messagingSenderId: '20913898706',
    projectId: 'sawit-pro-ea577',
    storageBucket: 'sawit-pro-ea577.appspot.com',
    iosClientId: '20913898706-kqc9k68oe1j8091s9ejldcvuso6bhs6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sawitproassessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhBZZdI3qEfnHkyZbgD7z4OxWcLu2WiVY',
    appId: '1:20913898706:ios:733207478120196545190b',
    messagingSenderId: '20913898706',
    projectId: 'sawit-pro-ea577',
    storageBucket: 'sawit-pro-ea577.appspot.com',
    iosClientId: '20913898706-kqc9k68oe1j8091s9ejldcvuso6bhs6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sawitproassessment',
  );
}
